// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_GR6bZJ3vBJDaJcHmzju29zAXwZF-Yt4',
    appId: '1:180332918273:web:a233ba2416287dc952f200',
    messagingSenderId: '180332918273',
    projectId: 'bondify-b52f7',
    authDomain: 'bondify-b52f7.firebaseapp.com',
    storageBucket: 'bondify-b52f7.firebasestorage.app',
    measurementId: 'G-XEMZLWVXVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1OHtsyDjLYmEa5ZyhFktskdNCqc7kyW0',
    appId: '1:180332918273:android:e018e9323e4f644452f200',
    messagingSenderId: '180332918273',
    projectId: 'bondify-b52f7',
    storageBucket: 'bondify-b52f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSjnwhYPtwcmQMwn57RlJoVWvRrmeX1aY',
    appId: '1:180332918273:ios:47bc973c3418283c52f200',
    messagingSenderId: '180332918273',
    projectId: 'bondify-b52f7',
    storageBucket: 'bondify-b52f7.firebasestorage.app',
    iosBundleId: 'com.example.bondifyfrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSjnwhYPtwcmQMwn57RlJoVWvRrmeX1aY',
    appId: '1:180332918273:ios:47bc973c3418283c52f200',
    messagingSenderId: '180332918273',
    projectId: 'bondify-b52f7',
    storageBucket: 'bondify-b52f7.firebasestorage.app',
    iosBundleId: 'com.example.bondifyfrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_GR6bZJ3vBJDaJcHmzju29zAXwZF-Yt4',
    appId: '1:180332918273:web:a7331a9e1ecef87c52f200',
    messagingSenderId: '180332918273',
    projectId: 'bondify-b52f7',
    authDomain: 'bondify-b52f7.firebaseapp.com',
    storageBucket: 'bondify-b52f7.firebasestorage.app',
    measurementId: 'G-MENTCPW340',
  );
}
